export const apiRoutes = {
  createUser: "/users",
  login: "/login",
  createCategory: "/categories",
  createExpense: "/expenses",
  deleteExpense: "/expenses",
  getCategories: "/categories/all",
  getExpenses: "/expenses/all",
  getTags: "/tags/all",
  createTag: "/tags",
  deleteTag: "/tags",
  deleteCategory: "/categories",
  updateCategory: "/categories",
  updateExpense: "/expenses",
  updateTag: "/tags",
  getTotalExpensesForPeriod: "/expenses/total",
};
